- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        allow_unauthenticated: yes
      changed_when: false
      when: ansible_distribution == 'Ubuntu'

  tasks:
    - include_tasks: tasks/os_settings.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/generate_OpenSSH_keypair.yml
