- name: Set timezone
  become: yes
  timezone:
    name: Europe/Berlin

- name: Make Wayland default
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sddm.conf
    regexp: '^Session='
    line: Session=plasmawayland.desktop

- name: Automatic Relogin after Logout
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sddm.conf
    state: present
    line: Relogin=true